export const FETCH_LIST_EMPLOYEE='FETCH_LIST_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const LIST_EMPLOYEE_BY_ID='LIST_EMPLOYEE_BY_ID';
export const FETCH_EMPLOYEE_FAIL='FETCH_EMPLOYEE_FAIL';
export const FETCH_EMPLOYEE_START='FETCH_EMPLOYEE_START';